framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            graber: '%env(GRABER_MESSENGER_TRANSPORT_DSN)%'
            failed_graber: '%env(GRABER_FAILED_MESSENGER_TRANSPORT_DSN)%'

        routing:
            App\Domain\Api\Domain\Message\GenerateArchive: graber
