index:
    path: /
    controller: App\Controller\MainController::indexAction

jsonrpc_entry_point:
    path: /api
    controller: App\Context\Api\Infrastructure\Controller\FrontController::entryPoint