index:
    path: /
    controller: App\Controller\MainController::indexAction

reset:
    path: /reset
    controller: App\Context\Api\Infrastructure\Controller\FrontController::resetAction

archive_file:
    path: /archive/{fileName}
    controller: App\Context\Api\Infrastructure\Controller\FrontController::archiveAction
    requirements:
        fileName: .+

jsonrpc_entry_point:
    prefix: /api
    resource: "@JSONRPCBundle/Resources/config/routing/routes.yaml"