parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    #Services
    App\Context\Parser\Application\Common\ProductParser\Parser:
        class: App\Context\Parser\Application\Common\ProductParser\ParserImplDecorated

    #Queries
    App\Context\Api\Application\Query\GetProcessStateHandler:
        public: true
        autowire: true
        class: App\Context\Api\Application\QueryHandler\GetProcessStateHandler

    #Commands
    App\Context\Api\Application\Command\StartProcessHandler:
        public: true
        autowire: true
        class: App\Context\Api\Application\CommandHandler\StartProcessHandler
    App\Context\Api\Application\Command\ResetProcessHandler:
        public: true
        autowire: true
        class: App\Context\Api\Application\CommandHandler\ResetProcessHandler
    App\Context\Api\Application\Command\GenerateArchiveHandler:
        public: true
        autowire: true
        class: App\Context\Api\Application\CommandHandler\GenerateArchiveHandler
    App\Context\Parser\Application\Command\ParseProductByURLHandler:
        public: true
        autowire: true
        class: App\Context\Parser\Application\CommandHandler\ParseProductByURLHandler
    App\Context\Parser\Application\Command\ParseCategoryProductsByCategoryURLHandler:
        public: true
        autowire: true
        class: App\Context\Parser\Application\CommandHandler\ParseCategoryProductsByCategoryURLHandler
    App\Context\Parser\Application\Command\DownloadProductsPicturesByCategoryURLHandler:
        public: true
        autowire: true
        class: App\Context\Parser\Application\CommandHandler\DownloadProductsPicturesByCategoryURLHandler
